const UPDATE_GLOBAL_INFO='UPDATE_GLOBAL_INFO'
const UPDATE_GOODS_INFO='UPDATE_GOODS_INFO'
const UPDATE_GOODS_INFO_ASYNC='UPDATE_GOODS_INFO_ASYNC'
const UPDATE_SELLER_INFO='UPDATE_SELLER_INFO'

export default {
	UPDATE_GLOBAL_INFO,
	UPDATE_GOODS_INFO,
	UPDATE_SELLER_INFO,
	UPDATE_GOODS_INFO_ASYNC
}